---
deployment:
  tasks:
    - /opt/cpanel/ea-php84/root/usr/bin/php composer.phar install --no-dev --no-interaction --prefer-dist
    - mkdir -p storage/framework/views storage/framework/cache/data storage/framework/sessions storage/logs bootstrap/cache
    - chmod -R 755 storage bootstrap/cache
    - /opt/cpanel/ea-php84/root/usr/bin/php artisan storage:link
    - /opt/cpanel/ea-php84/root/usr/bin/php artisan migrate --force --no-interaction
    - /opt/cpanel/ea-php84/root/usr/bin/php artisan config:cache
    - /opt/cpanel/ea-php84/root/usr/bin/php artisan route:cache
    - /opt/cpanel/ea-php84/root/usr/bin/php artisan view:cache
    - /opt/cpanel/ea-php84/root/usr/bin/php artisan event:cache
    - /opt/cpanel/ea-php84/root/usr/bin/php artisan permission:cache-reset
